### ISSUE TITLE
Publish 1.0

### ISSUE THREAD

**Issue by stjepang** [stjepang/futures-lite#10]
To prevent being stuck at 0.1 forever, I am considering publishing 1.0 rather sooner than later. The crate is 90% done anyway and I don't expect there will be many changes - just a few remaining additions.

The only breaking change I might do is rename `future::join()` to `future::zip()`. Thoughts?

**Comment by jjl** [comment]
I'd be in favour of that

**Comment by stjepang** [comment]
I have renamed `join()` to `zip()` and `try_join()` to `try_zip()`. Version 1.0.0 is now published.
