### ISSUE TITLE
io::Bytes AsyncRead

### ISSUE THREAD

**Issue by zethra** [stjepang/futures-lite#3]
I have a use case where I need a byte stream and async reader.  I currently have my own implementation of this that works fine but I was wondering if other might find this useful.  I could either add an AsyncRead impl to io::Bytes or create a separate type for this.  I wanted feedback before submitting a patch.  Thoughts?

**Comment by stjepang** [comment]
Adding an AsyncRead impl to Bytes sounds reasonable to me! I'm curious though - what does your own implementation look like?

**Comment by stjepang** [comment]
Implemented in the master branch.
