### ISSUE TITLE
Debug info printed to console in 1.11.0

### ISSUE THREAD

**Issue by Waridley** [stjepang/futures-lite#30]
You seem to have forgotten to remove some debug prints from the `poll_fill_buf` function:
https://github.com/stjepang/futures-lite/blob/f5faa76ab6c20a0aa5f27d4d7fb4f5faf4a5f4ec/src/io.rs#L619
https://github.com/stjepang/futures-lite/blob/f5faa76ab6c20a0aa5f27d4d7fb4f5faf4a5f4ec/src/io.rs#L627
https://github.com/stjepang/futures-lite/blob/f5faa76ab6c20a0aa5f27d4d7fb4f5faf4a5f4ec/src/io.rs#L630

**Comment by stjepang** [comment]
Fixed.
